version: "3"
services:
  reactapp:
    container_name: reactapp
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "cd reactapp && yarn start"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
