version: "3.8"
services:
  baufront:
    image: node:12.18.3-alpine3.12
    container_name: baufront
    volumes:
      - ./project:/project
    working_dir: /project
    tty: true
    ports:
      - 3000:3000
    command: yarn start

