version: "3"
services:
  reactapp:
    container_name: localstate
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    # <<初回>>
    #command: npx create-react-app reactapp --template typescript
    # <<２回目以降>>
    #command: sh -c "cd reactapp && yarn start"
